import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Full hand-authored nav. The API Reference items are auto-generated by
 * docusaurus-plugin-openapi-docs into docs/api-reference/sidebar.ts (gitignored); we require
 * it through a guard so a clean checkout can run gen-api first.
 */
let apiItems: any[] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  apiItems = require('./docs/api-reference/sidebar').default ?? [];
} catch {
  apiItems = [];
}

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      items: ['get-started/start-here', 'get-started/quickstart', 'get-started/introduction', 'get-started/access'],
    },
    {
      type: 'category',
      label: 'Integration',
      collapsed: false,
      items: [
        'integration/overview',
        'integration/payload',
        'integration/verify-webhooks',
        'integration/delivery',
        'integration/sizing',
        'integration/recipes',
        'integration/catalogue',
      ],
    },
    {
      type: 'category',
      label: 'Gaia',
      collapsed: false,
      items: [
        'gaia/overview',
        'gaia/data-model',
        'gaia/endpoints',
        'gaia/benchmark-methodology',
        'gaia/verify',
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      collapsed: false,
      items: ['recipes/evaluate-vs-your-book'],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'concepts/envelope',
        'concepts/verification',
        'concepts/error-codes',
        'concepts/rate-limits',
        'concepts/versioning',
      ],
    },
    {
      type: 'category',
      label: 'Methodology',
      items: [
        'methodology/overview',
        'methodology/risk-rescale',
        'methodology/metrics',
        'methodology/correlation',
        'methodology/fees-slippage',
        'methodology/provenance',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'generated-index', title: 'API Reference', slug: '/api-reference'},
      items: apiItems,
    },
    {
      type: 'category',
      label: 'Legal',
      items: ['legal/not-advice', 'legal/licensing'],
    },
    {
      type: 'category',
      label: 'Help',
      items: ['help/contact', 'help/changelog'],
    },
  ],
};

export default sidebars;
