import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Phase 1 (look-lock): autogenerated from the docs/ tree, which currently holds one sample
 * page. The full hand-authored nav (Get Started → Core Concepts → Methodology → API
 * Reference → Help) lands with content in a later phase.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
